### ISSUE TITLE
Problem with input naming and escaping

### ISSUE THREAD

**Issue by tlacroix** [tj-actions/bandit#18]
* bandit:

### Description

The documentation defines the "targets" variable to enter the path, but the `entrypoint.sh` script uses `$INPUT_PATH` on line 7. The documentation should either be updated to change the variable name to `path`, or the script changed to use the variable `$INPUT_TARGETS`.

Also, in the script, the `$INPUT` variables are enclosed in double quotes. This means that you can't specify multiple options or multiple paths, because it will end up like this (example with 2 options and 2 paths):

```bash
bandit "--recursive -lll" "path1/ path2/"
```

rather than like this:
```bash
bandit --recursive -lll path1/ path2/
```

### What I Did

To have it work, I had to use the following config:
```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Bandit
        uses: tj-actions/bandit@main
        with:
          bandit_version: "1.7.0"
          path: "."
          options: "-rlll"
```

... whereas, according to the documentation, this config should have worked, but it does not for the reasons mentioned in the description section:
```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Bandit
        uses: tj-actions/bandit@main
        with:
          bandit_version: "1.7.0"
          targets: "."
          options: "--recursive -lll"
```
